# Generated by Django 2.2 on 2020-08-05 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_shopuserprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuserprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'мужской'), ('F', 'женский')], default='M', max_length=1, verbose_name='пол'),
        ),
    ]
